apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.backend }}
  namespace: {{ .Values.app.backendnamespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.backend }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.backendcontainerPort }}
    targetPort: {{ .Values.app.backendcontainerPort }}