apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.mongodb }}-service
  namespace: {{ .Values.app.dbnamespace }}
spec:
  selector:
    app: {{ .Values.app.mongodb }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.mongodbcontainerPort }}
    targetPort: {{ .Values.app.mongodbcontainerPort }}
  type: ClusterIP
