apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.frontend }}
  namespace: {{ .Values.app.frontendnamespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.frontend }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.frontendcontainerPort }}
    targetPort: {{ .Values.app.frontendcontainerPort }}